import test from 'node:test';
import assert from 'node:assert/strict';
import {rebuildWardRegistryRow,rebuildWardRegistryForLm} from '../registry/wardBuilder.js';
import {affectedWardScopes} from '../registry/wardChangeScopes.js';
const zero={formalErfs:0,informalErfs:0,totalErfs:0,premises:0,electricityMeters:0,waterMeters:0,totalMeters:0,trns:0};
function database() {
 const values=new Map([['wards/W1',{code:1,name:'001',parents:{localMunicipalityId:'LM'}}],['wards/W2',{code:2,name:'002',parents:{localMunicipalityId:'LM'}}]]);
 function merge(a,b){const result={...a};for(const [k,v] of Object.entries(b))result[k]=v && Object.getPrototypeOf(v)===Object.prototype ? merge(a?.[k],v):v;return result;}
 const ref=path=>({path,id:path.split('/').pop()});
 const snap=r=>({id:r.id,exists:values.has(r.path),data:()=>values.get(r.path)});
 let queue=Promise.resolve();
 const db={collection:name=>({doc:id=>ref(name+'/'+id),where:()=>({get:async()=>({size:2,docs:['W1','W2'].map(id=>snap(ref('wards/'+id)))})})})};
 db.runTransaction=fn=>{const run=queue.then(()=>fn({get:async r=>snap(r),set:(r,v)=>values.set(r.path,merge(values.get(r.path),v)),delete:r=>values.delete(r.path)}));queue=run.catch(()=>{});return run;};
 return {db,values};
}
test('successful zero has READY state and saved successful values',async()=>{const {db,values}=database();await rebuildWardRegistryRow({db,lmPcode:'LM',wardPcode:'W1',countLoader:async()=>zero});const row=values.get('registry_wards/LM__W1');assert.equal(row.calculation.state,'READY');assert.equal(row.counts.totalErfs,0);assert.deepEqual(row.lastSuccessfulCounts,zero);});
test('failure retains previous successful values but explicitly marks unavailable',async()=>{const {db,values}=database();const args={db,lmPcode:'LM',wardPcode:'W1'};await rebuildWardRegistryRow({...args,countLoader:async()=>zero});await assert.rejects(rebuildWardRegistryRow({...args,countLoader:async()=>{throw new Error('offline');}}));assert.equal(values.get('registry_wards/LM__W1').calculation.state,'UNAVAILABLE');assert.deepEqual(values.get('registry_wards/LM__W1').lastSuccessfulCounts,zero);await rebuildWardRegistryRow({...args,countLoader:async()=>zero});assert.equal(values.get('registry_wards/LM__W1').calculation.state,'READY');});
test('older calculation cannot overwrite newer completed request',async()=>{const {db,values}=database();let release,started;const ready=new Promise(r=>started=r);const old=rebuildWardRegistryRow({db,lmPcode:'LM',wardPcode:'W1',countLoader:()=>{started();return new Promise(r=>release=r);}});await ready;assert.equal(values.get('registry_wards/LM__W1').calculation.state,'PENDING');await rebuildWardRegistryRow({db,lmPcode:'LM',wardPcode:'W1',countLoader:async()=>({...zero,formalErfs:5,totalErfs:5})});release(zero);assert.equal((await old).published,false);assert.equal(values.get('registry_wards/LM__W1').counts.totalErfs,5);});
test('invalid counters fail instead of publishing zero',async()=>{const {db,values}=database();await assert.rejects(rebuildWardRegistryRow({db,lmPcode:'LM',wardPcode:'W1',countLoader:async()=>({...zero,totalErfs:undefined})}));assert.equal(values.get('registry_wards/LM__W1').calculation.state,'UNAVAILABLE');});
test('bulk rebuild continues other wards and reports failures',async()=>{const {db}=database();const visited=[];await assert.rejects(rebuildWardRegistryForLm('LM',{db,rebuild:async({wardPcode})=>{visited.push(wardPcode);if(wardPcode==='W1')throw new Error('failure');}}),e=>e.result.completed===1 && e.result.failed[0]==='W1');assert.deepEqual(visited,['W1','W2']);});
test('creation deletion and transfers refresh exactly affected wards; irrelevant edits do not',()=>{for(const kind of ['premises','asts','trns','ireps_erfs','wards']){const make=ward=>kind==='wards'?{parents:{localMunicipalityId:ward},code:1}:kind==='ireps_erfs'?{admin:{localMunicipality:{pcode:'LM'},ward:{pcode:ward}},erf:{type:'FORMAL'}}:kind==='premises'?{parents:{lmPcode:'LM',wardPcode:ward}}:{accessData:{parents:{lmPcode:'LM',wardPcode:ward}},meterType:'electricity',status:'FIELD'};const before=make('W1'),after=make('W2');assert.equal(affectedWardScopes(kind,null,before,'W1').length,1);assert.equal(affectedWardScopes(kind,before,null,'W1').length,1);assert.equal(affectedWardScopes(kind,before,after,'W1').length,2);assert.equal(affectedWardScopes(kind,before,{...before,metadata:{updatedAt:'later'}},'W1').length,0);}});
