const styles = {
  page: { display: "grid", gap: 16, padding: "24px 28px 64px", color: "#0f172a" },
  backRow: { display: "flex", alignItems: "center", gap: 14, flexWrap: "wrap" },
  backLink: { color: "#1d4ed8", fontWeight: 900, textDecoration: "none" },
  header: {
    display: "flex", justifyContent: "space-between", alignItems: "flex-start",
    gap: 16, padding: "22px 24px", border: "1px solid #dbe4f0",
    borderRadius: 22, background: "#ffffff", flexWrap: "wrap",
  },
  eyebrow: { margin: 0, color: "#2563eb", fontSize: 12, fontWeight: 900, letterSpacing: "0.08em", textTransform: "uppercase" },
  title: { margin: "8px 0 6px", fontSize: 30, color: "#0f172a" },
  subtitle: { maxWidth: 880, margin: 0, color: "#64748b", lineHeight: 1.55 },
  badge: { display: "inline-flex", alignItems: "center", width: "fit-content", borderRadius: 999, padding: "5px 9px", fontSize: 10, fontWeight: 900, letterSpacing: "0.02em", whiteSpace: "nowrap" },
  successBadge: { background: "#dcfce7", color: "#166534" },
  warningBadge: { background: "#fef3c7", color: "#92400e" },
  dangerBadge: { background: "#fee2e2", color: "#991b1b" },
  infoBadge: { background: "#dbeafe", color: "#1d4ed8" },
  neutralBadge: { background: "#e2e8f0", color: "#475569" },
  summaryPanel: { display: "grid", gridTemplateColumns: "minmax(260px, 0.72fr) minmax(0, 1.7fr)", gap: 16, padding: 16, border: "1px solid #dbe4f0", borderRadius: 22, background: "#ffffff" },
  summaryMetaColumn: { display: "grid", gap: 10, padding: 14, border: "1px solid #e2e8f0", borderRadius: 16, background: "#f8fafc" },
  summaryDetailRow: { display: "grid", gap: 4 },
  summaryDetailLabel: { color: "#64748b", fontSize: 10, fontWeight: 900, letterSpacing: "0.06em", textTransform: "uppercase" },
  summaryDetailValue: { color: "#0f172a", fontSize: 13, wordBreak: "break-word" },
  summaryMetricGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 10 },
  infoCard: { padding: 13, border: "1px solid #e2e8f0", borderRadius: 16, background: "#f8fafc" },
  infoLabel: { display: "block", marginBottom: 6, color: "#64748b", fontSize: 10, fontWeight: 900, letterSpacing: "0.05em", textTransform: "uppercase" },
  infoValue: { display: "block", color: "#0f172a", fontSize: 14, lineHeight: 1.4, wordBreak: "break-word" },
  infoDetail: { display: "block", marginTop: 4, color: "#64748b", fontSize: 11 },
  infoBanner: { padding: "14px 16px", border: "1px solid #93c5fd", borderRadius: 16, background: "#eff6ff", color: "#1e3a8a", lineHeight: 1.55 },
  previewBanner: { borderColor: "#fbbf24", background: "#fffbeb", color: "#92400e" },
  notice: { padding: 14, border: "1px solid #bfdbfe", borderRadius: 14, background: "#eff6ff", color: "#1e3a8a" },
  errorNotice: { padding: 14, border: "1px solid #fecaca", borderRadius: 14, background: "#fef2f2", color: "#991b1b" },
  noticeText: { margin: "8px 0 0", lineHeight: 1.55 },
  boardGrid: { display: "grid", gridTemplateColumns: "minmax(310px, 0.78fr) minmax(0, 1.72fr)", gap: 16, alignItems: "start" },
  leftColumn: { minWidth: 0 },
  panel: { minWidth: 0, padding: 16, border: "1px solid #dbe4f0", borderRadius: 22, background: "#ffffff" },
  panelHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 14, flexWrap: "wrap" },
  panelTitle: { margin: 0, color: "#0f172a", fontSize: 18 },
  panelSubtitle: { maxWidth: 840, margin: "5px 0 0", color: "#64748b", lineHeight: 1.5 },
  targetToggleRow: { display: "flex", gap: 8, marginBottom: 12 },
  targetToggleButton: { flex: 1, border: "1px solid #cbd5e1", borderRadius: 999, padding: "9px 12px", background: "#ffffff", color: "#475569", fontWeight: 900, cursor: "pointer" },
  targetToggleActive: { borderColor: "#2563eb", background: "#eff6ff", color: "#1d4ed8" },
  targetOptionList: { display: "grid", gap: 10, maxHeight: 650, overflowY: "auto", paddingRight: 3 },
  targetOptionCard: { width: "100%", display: "grid", gap: 8, padding: 12, border: "1px solid #dbe4f0", borderRadius: 16, background: "#f8fafc", color: "#0f172a", textAlign: "left", cursor: "grab" },
  targetOptionCardActive: { borderColor: "#2563eb", background: "#eff6ff", boxShadow: "0 0 0 2px rgba(37, 99, 235, 0.1)" },
  targetOptionHeader: { display: "flex", alignItems: "center", gap: 8 },
  targetType: { borderRadius: 999, padding: "3px 7px", background: "#dbeafe", color: "#1d4ed8", fontSize: 9, fontWeight: 900 },
  targetTitle: { color: "#0f172a", fontSize: 14 },
  targetSub: { margin: 0, color: "#64748b", fontSize: 12, lineHeight: 1.45 },
  targetMicro: { color: "#64748b", fontSize: 10, fontWeight: 800 },
  memberList: { display: "flex", gap: 5, flexWrap: "wrap" },
  memberChip: { display: "grid", gap: 1, maxWidth: "100%", padding: "4px 6px", border: "1px solid #cbd5e1", borderRadius: 9, background: "#ffffff", color: "#334155", fontSize: 9 },
  memberChipWarning: { borderColor: "#fbbf24", background: "#fffbeb" },
  memberMore: { alignSelf: "center", color: "#64748b", fontSize: 10, fontWeight: 800 },
  memberEmpty: { color: "#94a3b8", fontSize: 10 },

  groupList: { display: "grid", gap: 12 },
  groupHeaderRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, flexWrap: "wrap" },
  groupMetricRow: { display: "flex", gap: 8, marginTop: 10, color: "#475569", fontSize: 11, fontWeight: 800, flexWrap: "wrap" },
  groupCard: { padding: 14, border: "1px solid #dbe4f0", borderRadius: 18, background: "#f8fafc", transition: "border-color 120ms ease, background 120ms ease, box-shadow 120ms ease" },
  groupCardActive: { borderColor: "#2563eb", background: "#eff6ff", boxShadow: "0 0 0 2px rgba(37, 99, 235, 0.1)" },
  groupCardAllocated: { borderColor: "#86efac", background: "#f0fdf4" },
  groupCardDragFocused: { borderColor: "#16a34a", background: "#dcfce7", boxShadow: "0 0 0 3px rgba(22, 163, 74, 0.12)" },
  groupMain: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(230px, 0.8fr)", gap: 12, alignItems: "stretch" },
  groupSelectButton: { width: "100%", display: "grid", gap: 6, padding: 12, border: 0, borderRadius: 14, background: "#ffffff", color: "#0f172a", textAlign: "left", cursor: "pointer" },
  groupName: { fontSize: 15, fontWeight: 900 },
  groupMeta: { color: "#64748b", fontSize: 11, fontWeight: 800 },
  groupAllocationBox: { display: "grid", gap: 5, alignContent: "center", padding: 12, border: "2px dashed #93c5fd", borderRadius: 14, background: "#eff6ff" },
  groupAllocationBoxAssigned: { borderStyle: "solid", borderColor: "#86efac", background: "#dcfce7" },
  groupAllocationBoxDragFocused: { borderColor: "#16a34a", background: "#bbf7d0" },
  groupAllocationLabel: { color: "#64748b", fontSize: 9, fontWeight: 900, letterSpacing: "0.06em", textTransform: "uppercase" },
  groupAllocationTarget: { color: "#0f172a", fontSize: 13 },
  groupAllocationMembers: { color: "#475569", fontSize: 10, fontWeight: 750 },
  groupActions: { display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 10, flexWrap: "wrap" },
  filterRow: { display: "flex", gap: 7, marginBottom: 12, flexWrap: "wrap" },
  filterButton: { border: "1px solid #cbd5e1", borderRadius: 999, padding: "7px 10px", background: "#ffffff", color: "#475569", fontWeight: 850, cursor: "pointer" },
  filterButtonActive: { borderColor: "#2563eb", background: "#eff6ff", color: "#1d4ed8" },
  rowSearchBar: { display: "flex", justifyContent: "space-between", alignItems: "end", gap: 12, marginBottom: 12, flexWrap: "wrap" },
  searchLabel: { display: "grid", gap: 5, color: "#475569", fontSize: 11, fontWeight: 850 },
  searchInput: { minWidth: 240, border: "1px solid #cbd5e1", borderRadius: 10, padding: "8px 10px", color: "#0f172a" },
  pageSizeLabel: { display: "flex", alignItems: "center", gap: 7, color: "#475569", fontSize: 11, fontWeight: 850 },
  select: { border: "1px solid #cbd5e1", borderRadius: 10, padding: "8px 10px", background: "#ffffff", color: "#0f172a" },
  assignmentDropZone: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 14, marginBottom: 12, padding: 14, border: "2px dashed #93c5fd", borderRadius: 16, background: "#eff6ff", flexWrap: "wrap" },
  assignmentDropZoneActive: { borderColor: "#16a34a", background: "#f0fdf4", boxShadow: "0 0 0 3px rgba(22, 163, 74, 0.1)" },
  dropZoneTitle: { color: "#0f172a" },
  dropZoneText: { margin: "4px 0 0", color: "#1e3a8a", fontWeight: 800 },
  dropZoneHint: { margin: "4px 0 0", color: "#64748b", fontSize: 11 },
  assignmentActions: { display: "flex", gap: 8, flexWrap: "wrap" },
  primaryButton: { border: "1px solid #1d4ed8", borderRadius: 11, padding: "9px 12px", background: "#2563eb", color: "#ffffff", fontWeight: 900, cursor: "pointer" },
  secondaryButton: { border: "1px solid #cbd5e1", borderRadius: 11, padding: "9px 12px", background: "#ffffff", color: "#334155", fontWeight: 900, cursor: "pointer" },
  disabledButton: { opacity: 0.55, cursor: "not-allowed" },
  statusMessage: { marginBottom: 12, padding: "9px 11px", borderRadius: 10, background: "#f1f5f9", color: "#475569", fontSize: 12, fontWeight: 750 },
  emptyState: { padding: 16, border: "1px dashed #cbd5e1", borderRadius: 14, background: "#f8fafc", color: "#64748b" },
  tableWrap: { width: "100%", overflowX: "auto", border: "1px solid #e2e8f0", borderRadius: 14 },
  table: { width: "100%", minWidth: 1180, borderCollapse: "separate", borderSpacing: 0, fontSize: 12 },
  th: { position: "sticky", top: 0, zIndex: 2, padding: "9px 10px", borderRight: "1px solid #cbd5e1", borderBottom: "1px solid #cbd5e1", background: "#e2e8f0", color: "#0f172a", textAlign: "left", whiteSpace: "nowrap" },
  td: { padding: "9px 10px", borderRight: "1px solid #e2e8f0", borderBottom: "1px solid #e2e8f0", background: "#ffffff", color: "#334155", verticalAlign: "top" },
  strongCell: { color: "#0f172a", fontWeight: 850 },
  allocationCell: { display: "grid", gap: 5 },
  allocationTargetPill: { display: "inline-flex", width: "fit-content", maxWidth: 260, borderRadius: 999, padding: "4px 7px", fontSize: 10, fontWeight: 850, whiteSpace: "normal" },
  allocationTargetPillTeam: { background: "#dbeafe", color: "#1d4ed8" },
  allocationTargetPillSp: { background: "#dcfce7", color: "#166534" },
  trnIdText: { marginTop: 5, color: "#475569", fontSize: 10, wordBreak: "break-word" },
  rowSourceIdentity: { marginTop: 4, maxWidth: 280, color: "#64748b", fontSize: 9, fontWeight: 700, wordBreak: "break-all" },
  codeText: { display: "inline-block", width: "fit-content", maxWidth: "100%", padding: "2px 5px", borderRadius: 6, background: "#e2e8f0", color: "#0f172a", fontSize: 10, fontWeight: 900, wordBreak: "break-all" },
  rowReferenceList: { display: "grid", gap: 6, minWidth: 250, maxHeight: 180, overflowY: "auto" },
  rowReferenceItem: { display: "grid", gap: 2, padding: "6px 8px", border: "1px solid #e2e8f0", borderRadius: 9, background: "#f8fafc", color: "#334155", fontSize: 10 },
  paginationBar: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginTop: 12, color: "#64748b", fontSize: 11, flexWrap: "wrap" },
  paginationControls: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  paginationButton: { border: "1px solid #cbd5e1", borderRadius: 9, padding: "6px 9px", background: "#ffffff", color: "#334155", fontWeight: 800, cursor: "pointer" },
  clearAssignmentButton: { border: "1px solid #fecaca", borderRadius: 9, padding: "6px 9px", background: "#fff1f2", color: "#b91c1c", fontWeight: 850, cursor: "pointer" },
  createPanel: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, padding: 18, border: "1px solid #dbe4f0", borderRadius: 22, background: "#f8fafc", flexWrap: "wrap" },
  createMetrics: { display: "flex", gap: 8, marginTop: 10, flexWrap: "wrap" },
  createButton: { border: "1px solid #166534", borderRadius: 12, padding: "11px 15px", background: "#16a34a", color: "#ffffff", fontWeight: 900 },
  stepPanel: { display: "grid", gap: 14 },
  stepHeader: { display: "grid", gridTemplateColumns: "44px minmax(0, 1fr) auto", gap: 12, alignItems: "start" },
  stepNumber: { display: "inline-flex", alignItems: "center", justifyContent: "center", width: 36, height: 36, borderRadius: 999, background: "#2563eb", color: "#ffffff", fontSize: 16, fontWeight: 900 },
  salesFlowBanner: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", padding: "13px 15px", border: "1px solid #86efac", borderRadius: 16, background: "#f0fdf4", color: "#166534", fontSize: 12, fontWeight: 800 },
  targetChoiceGrid: { display: "grid", gridTemplateColumns: "minmax(260px, 0.8fr) minmax(300px, 1.2fr)", gap: 14, alignItems: "end" },
  targetChoiceColumn: { display: "grid", gap: 7 },
  fieldLabel: { color: "#64748b", fontSize: 10, fontWeight: 900, letterSpacing: "0.06em", textTransform: "uppercase" },
  targetSelect: { width: "100%", minHeight: 42, border: "1px solid #cbd5e1", borderRadius: 11, padding: "9px 11px", background: "#ffffff", color: "#0f172a", fontWeight: 800 },
  selectedTargetCard: { display: "grid", gap: 10, padding: 14, border: "1px solid #86efac", borderRadius: 16, background: "#f0fdf4" },
  selectedTargetHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, flexWrap: "wrap" },
  selectedTargetName: { display: "block", marginTop: 4, color: "#0f172a", fontSize: 15 },
  targetInstruction: { padding: 13, border: "1px dashed #93c5fd", borderRadius: 14, background: "#eff6ff", color: "#1e3a8a", lineHeight: 1.5 },
  assignmentBar: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 14, padding: 14, border: "1px solid #93c5fd", borderRadius: 16, background: "#eff6ff", flexWrap: "wrap" },
  assignmentBarSummary: { display: "grid", gap: 4 },
  assignmentTargetText: { color: "#0f172a", fontSize: 14 },
  assignmentRowCount: { color: "#1e3a8a", fontSize: 12, fontWeight: 900 },
  actionWarning: { padding: "10px 12px", border: "1px solid #fbbf24", borderRadius: 12, background: "#fffbeb", color: "#92400e", fontSize: 12, fontWeight: 800 },
  deferredPanel: { display: "grid", gap: 12, maxWidth: 900, padding: 24, border: "1px solid #fbbf24", borderRadius: 22, background: "#fffbeb" },
  primaryLinkButton: { display: "inline-flex", width: "fit-content", borderRadius: 12, padding: "10px 14px", background: "#2563eb", color: "#ffffff", fontWeight: 900, textDecoration: "none" },

};

export default styles;
