export const draftReviewStyles = {
  panel: {
    background: "#ffffff",
    border: "1px solid rgba(148, 163, 184, 0.28)",
    borderRadius: "1rem",
    boxShadow: "0 14px 30px rgba(15, 23, 42, 0.06)",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "1rem",
    padding: "1rem",
    flexWrap: "wrap",
  },
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    flexWrap: "wrap",
  },
  eyebrow: {
    margin: 0,
    color: "#2563eb",
    fontSize: "0.72rem",
    fontWeight: 900,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  title: {
    margin: "0.25rem 0 0",
    color: "#0f172a",
  },
  subtitle: {
    margin: "0.35rem 0 0",
    color: "#64748b",
  },
  sourceBadge: {
    borderRadius: "999px",
    padding: "0.18rem 0.5rem",
    fontSize: "0.68rem",
    fontWeight: 900,
    textTransform: "uppercase",
  },
  salesBadge: {
    background: "#dbeafe",
    color: "#1d4ed8",
  },
  uploadBadge: {
    background: "#fef3c7",
    color: "#92400e",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    flexWrap: "wrap",
  },
  statusBadge: {
    borderRadius: "999px",
    padding: "0.42rem 0.65rem",
    fontSize: "0.72rem",
    fontWeight: 900,
    textTransform: "uppercase",
  },
  draftStatus: {
    background: "#f1f5f9",
    color: "#475569",
  },
  readyStatus: {
    background: "#dcfce7",
    color: "#166534",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "0.65rem",
    padding: "0 1rem 1rem",
  },
  summaryCard: {
    display: "flex",
    flexDirection: "column",
    gap: "0.3rem",
    minWidth: 0,
    padding: "0.8rem",
    border: "1px solid #e2e8f0",
    borderRadius: "0.75rem",
    background: "#f8fafc",
    color: "#64748b",
  },
  summaryValue: {
    color: "#0f172a",
    fontSize: "1rem",
    overflowWrap: "anywhere",
  },
  sourceNotice: {
    margin: "0 1rem 1rem",
    padding: "0.85rem",
    border: "1px solid #bfdbfe",
    borderRadius: "0.75rem",
    background: "#eff6ff",
    color: "#1e3a8a",
  },
  sourceNoticeParagraph: {
    margin: "0.35rem 0 0",
    lineHeight: 1.5,
  },
  integrityPanel: {
    margin: "0 1rem 1rem",
    padding: "0.85rem",
    border: "1px solid #fecaca",
    borderRadius: "0.75rem",
    background: "#fff1f2",
    color: "#991b1b",
  },
  integrityList: {
    margin: "0.5rem 0 0",
    paddingLeft: "1.1rem",
  },
  filtersPanel: {
    display: "grid",
    gap: "0.75rem",
    padding: "1rem",
    borderTop: "1px solid #e2e8f0",
    background: "#f8fafc",
  },
  filtersHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "0.75rem",
    flexWrap: "wrap",
  },
  filtersTitle: {
    margin: 0,
    color: "#0f172a",
    fontSize: "0.9rem",
  },
  filtersCount: {
    color: "#64748b",
    fontSize: "0.78rem",
    fontWeight: 800,
  },
  filtersGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(220px, 2fr) repeat(2, minmax(150px, 1fr)) auto",
    gap: "0.65rem",
    alignItems: "end",
  },
  filterLabel: {
    display: "grid",
    gap: "0.35rem",
    color: "#475569",
    fontSize: "0.76rem",
    fontWeight: 800,
  },
  filterInput: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #cbd5e1",
    borderRadius: "0.6rem",
    padding: "0.55rem 0.65rem",
    background: "#ffffff",
    color: "#0f172a",
  },
  tableWrap: {
    width: "100%",
    maxHeight: "62vh",
    overflow: "auto",
    borderTop: "1px solid #e2e8f0",
    borderBottom: "1px solid #e2e8f0",
  },
  table: {
    width: "100%",
    minWidth: "2050px",
    borderCollapse: "separate",
    borderSpacing: 0,
    fontSize: "0.8rem",
  },
  headerCell: {
    position: "sticky",
    top: 0,
    zIndex: 2,
    padding: "0.65rem",
    borderRight: "1px solid #cbd5e1",
    borderBottom: "1px solid #cbd5e1",
    background: "#e2e8f0",
    color: "#0f172a",
    textAlign: "left",
    whiteSpace: "nowrap",
  },
  bodyCell: {
    padding: "0.65rem",
    borderRight: "1px solid #e2e8f0",
    borderBottom: "1px solid #e2e8f0",
    background: "#ffffff",
    color: "#334155",
    verticalAlign: "top",
  },
  idCell: {
    maxWidth: "220px",
    color: "#1d4ed8",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    overflowWrap: "anywhere",
  },
  meterCell: {
    fontWeight: 900,
    color: "#0f172a",
    whiteSpace: "nowrap",
  },
  addressCell: {
    minWidth: "260px",
  },
  sgCell: {
    minWidth: "220px",
    overflowWrap: "anywhere",
  },
  reasonCell: {
    minWidth: "220px",
  },
  moneyCell: {
    textAlign: "right",
    whiteSpace: "nowrap",
  },
  noRowsCell: {
    padding: "2rem",
    textAlign: "center",
    color: "#64748b",
    background: "#ffffff",
  },
  paginationBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "1rem",
    padding: "0.75rem 0.9rem",
    flexWrap: "wrap",
  },
  paginationSummary: {
    color: "#64748b",
    fontSize: "0.82rem",
  },
  paginationControls: {
    display: "flex",
    alignItems: "center",
    gap: "0.45rem",
    flexWrap: "wrap",
  },
  pageSizeLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.4rem",
    color: "#64748b",
    fontSize: "0.82rem",
    fontWeight: 700,
  },
  pageSizeSelect: {
    border: "1px solid rgba(148, 163, 184, 0.45)",
    borderRadius: "0.55rem",
    padding: "0.34rem 0.45rem",
    fontSize: "0.82rem",
  },
  paginationButton: {
    border: "1px solid rgba(148, 163, 184, 0.42)",
    background: "#ffffff",
    color: "#0f172a",
    borderRadius: "0.6rem",
    padding: "0.36rem 0.58rem",
    fontWeight: 800,
    cursor: "pointer",
  },
  pageCountLabel: {
    color: "#334155",
    fontSize: "0.82rem",
    fontWeight: 800,
    padding: "0 0.2rem",
  },
  confirmPanel: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "1rem",
    padding: "1rem",
    background: "#f8fafc",
    flexWrap: "wrap",
  },
  confirmText: {
    margin: "0.35rem 0 0",
    maxWidth: "760px",
    color: "#64748b",
    lineHeight: 1.5,
  },
  primaryButton: {
    border: "1px solid #1d4ed8",
    borderRadius: "0.7rem",
    padding: "0.55rem 0.8rem",
    background: "#2563eb",
    color: "#ffffff",
    fontWeight: 850,
    cursor: "pointer",
  },
  disabledButton: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  secondaryButton: {
    border: "1px solid #cbd5e1",
    borderRadius: "0.7rem",
    padding: "0.55rem 0.8rem",
    background: "#ffffff",
    color: "#334155",
    fontWeight: 850,
    cursor: "pointer",
  },
  dangerButton: {
    border: "1px solid #fecaca",
    borderRadius: "0.7rem",
    padding: "0.55rem 0.8rem",
    background: "#fff1f2",
    color: "#b91c1c",
    fontWeight: 850,
    cursor: "pointer",
  },
  filtersGridWithDecision: {
    gridTemplateColumns:
      "minmax(220px, 2fr) repeat(3, minmax(145px, 1fr)) auto",
  },
  rowDecisionBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "4.4rem",
    borderRadius: "999px",
    padding: "0.22rem 0.5rem",
    fontSize: "0.7rem",
    fontWeight: 900,
  },
  rowAcceptBadge: {
    background: "#dcfce7",
    color: "#166534",
  },
  rowRejectBadge: {
    background: "#fee2e2",
    color: "#991b1b",
  },
  rejectionCell: {
    minWidth: "280px",
    color: "#991b1b",
    overflowWrap: "anywhere",
  },
  confirmActions: {
    display: "flex",
    gap: "0.65rem",
    alignItems: "center",
    flexWrap: "wrap",
  },

};
