export const tbRowsStyles = {
  page: { padding: 24 },
  topActionRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  backLink: { color: "#1d4ed8", fontWeight: 900, textDecoration: "none" },
  actionLink: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #bfdbfe",
    borderRadius: 12,
    background: "#eff6ff",
    color: "#1d4ed8",
    padding: "9px 12px",
    fontWeight: 900,
    textDecoration: "none",
  },
  allocationLink: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #86efac",
    borderRadius: 12,
    background: "#dcfce7",
    color: "#166534",
    padding: "9px 12px",
    fontWeight: 900,
    textDecoration: "none",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 18,
    flexWrap: "wrap",
  },
  eyebrow: {
    margin: 0,
    color: "#2563eb",
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  title: { margin: "8px 0 6px", fontSize: 30, color: "#0f172a" },
  subtitle: { margin: 0, color: "#64748b", lineHeight: 1.5 },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: 999,
    padding: "7px 10px",
    fontSize: 11,
    fontWeight: 900,
  },
  infoPanel: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 22,
    padding: 16,
    marginBottom: 16,
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
    gap: 10,
  },
  infoItem: {
    border: "1px solid #e2e8f0",
    borderRadius: 13,
    background: "#f8fafc",
    padding: 11,
  },
  infoLabel: {
    display: "block",
    color: "#64748b",
    fontSize: 11,
    fontWeight: 900,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 5,
  },
  infoValue: {
    display: "block",
    color: "#0f172a",
    fontSize: 13,
    lineHeight: 1.4,
    wordBreak: "break-word",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(145px, 1fr))",
    gap: 10,
    marginBottom: 16,
  },
  summaryCard: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: 14,
  },
  summaryLabel: {
    display: "block",
    fontSize: 11,
    fontWeight: 900,
    color: "#64748b",
    marginBottom: 7,
  },
  summaryValue: { fontSize: 22, color: "#0f172a" },
  panel: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 22,
    padding: 16,
  },
  panelHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
    flexWrap: "wrap",
  },
  panelTitle: { margin: 0, fontSize: 18, color: "#0f172a" },
  panelSubtitle: { margin: "6px 0 0", color: "#64748b", fontSize: 13 },
  panelActions: { display: "flex", gap: 8, flexWrap: "wrap" },
  secondaryButton: {
    border: "1px solid #cbd5e1",
    borderRadius: 11,
    background: "#ffffff",
    color: "#334155",
    padding: "9px 11px",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
  },
  primaryButton: {
    border: "1px solid #1d4ed8",
    borderRadius: 11,
    background: "#2563eb",
    color: "#ffffff",
    padding: "9px 11px",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
  },
  filtersGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 10,
    marginBottom: 14,
    padding: 12,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: 14,
  },
  filterLabel: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
    color: "#475569",
    fontSize: 11,
    fontWeight: 900,
  },
  filterControl: {
    border: "1px solid #cbd5e1",
    borderRadius: 10,
    background: "#ffffff",
    padding: "9px 10px",
    minWidth: 0,
  },
  tableWrap: { overflowX: "auto" },
  table: { width: "100%", borderCollapse: "collapse", minWidth: 2700 },
  th: {
    textAlign: "left",
    fontSize: 11,
    color: "#475569",
    background: "#f8fafc",
    borderBottom: "1px solid #e2e8f0",
    padding: "11px 9px",
    whiteSpace: "nowrap",
  },
  td: {
    fontSize: 12,
    color: "#334155",
    borderBottom: "1px solid #f1f5f9",
    padding: "11px 9px",
    verticalAlign: "top",
  },
  strongCell: { color: "#0f172a", fontWeight: 900 },
  mutedText: { color: "#94a3b8" },
  referenceStack: { display: "grid", gap: 4, minWidth: 210 },
  referenceLine: { fontSize: 11, color: "#475569", wordBreak: "break-word" },
  statusBadge: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: 999,
    padding: "5px 8px",
    fontSize: 10,
    fontWeight: 900,
    whiteSpace: "nowrap",
  },
  paginationBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    paddingTop: 14,
    flexWrap: "wrap",
  },
  paginationSummary: { color: "#64748b", fontSize: 12 },
  paginationControls: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    flexWrap: "wrap",
  },
  pageSizeLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    color: "#64748b",
    fontSize: 12,
    fontWeight: 800,
  },
  pageSizeSelect: {
    border: "1px solid #cbd5e1",
    borderRadius: 9,
    background: "#ffffff",
    padding: "7px 8px",
  },
  paginationButton: {
    border: "1px solid #cbd5e1",
    borderRadius: 9,
    background: "#ffffff",
    color: "#334155",
    padding: "7px 8px",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  },
  pageCountLabel: { color: "#475569", fontSize: 12, fontWeight: 800 },
  notice: {
    padding: 16,
    border: "1px solid #e2e8f0",
    borderRadius: 15,
    background: "#f8fafc",
    color: "#475569",
  },
  errorNotice: {
    padding: 18,
    border: "1px solid #fecaca",
    borderRadius: 18,
    background: "#fef2f2",
    color: "#991b1b",
  },
  noticeText: { margin: "8px 0 0", lineHeight: 1.5 },
};
