export const REGISTRY_MREAD_COLLECTION = "registry_mread";

export const MREAD_OUTCOMES = Object.freeze({
  SUCCESSFUL_READING: "SUCCESSFUL_READING",
  UNSUCCESSFUL_READING: "UNSUCCESSFUL_READING",
  NO_ACCESS: "NO_ACCESS",
});

export const CANONICAL_MREAD_OUTCOMES = Object.freeze([
  MREAD_OUTCOMES.SUCCESSFUL_READING,
  MREAD_OUTCOMES.UNSUCCESSFUL_READING,
  MREAD_OUTCOMES.NO_ACCESS,
]);

export const CANONICAL_MREAD_OUTCOME_SET = new Set(CANONICAL_MREAD_OUTCOMES);

export const MREAD_BILLING_READINESS = Object.freeze({
  BILLING_READY_CANDIDATE: "BILLING_READY_CANDIDATE",
  BILLING_REVIEW_REQUIRED: "BILLING_REVIEW_REQUIRED",
  NOT_BILLING_READY: "NOT_BILLING_READY",
});

export const MREAD_REVIEW_STATUS = Object.freeze({
  NAv: "NAv",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
});

export const MREAD_STREAM_TYPES = Object.freeze({
  UNCONTROLLED: "UNCONTROLLED",
  CONTROLLED_INDIVIDUAL: "CONTROLLED_INDIVIDUAL",
  CONTROLLED_BGO: "CONTROLLED_BGO",
  UNKNOWN_REVIEW: "UNKNOWN_REVIEW",
});

// For controlled migration/backfill scripts only. Do not use this map inside
// writeRegistryMreadFromTrn() or mapTrnMreadToRegistryMread().
export const LEGACY_MREAD_OUTCOME_MAP = Object.freeze({
  SUCCESS: MREAD_OUTCOMES.SUCCESSFUL_READING,
  NO_READING: MREAD_OUTCOMES.UNSUCCESSFUL_READING,
  NO_ACCESS: MREAD_OUTCOMES.NO_ACCESS,
});

export function isCanonicalMreadOutcome(outcome) {
  return CANONICAL_MREAD_OUTCOME_SET.has(String(outcome || "").trim());
}
