const styles = {
  page: {
    display: "grid",
    gap: 20,
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    overflowX: "hidden",
    padding: 24,
  },
  hero: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "flex-start",
    flexWrap: "wrap",
    minWidth: 0,
    padding: 24,
    borderRadius: 24,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    boxShadow: "0 18px 45px rgba(15, 23, 42, 0.08)",
  },
  heroActions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  eyebrow: {
    margin: 0,
    color: "#64748b",
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  title: {
    margin: "8px 0 0",
    color: "#0f172a",
    fontSize: 28,
    lineHeight: 1.1,
  },
  description: {
    margin: "10px 0 0",
    color: "#475569",
    maxWidth: 820,
    lineHeight: 1.55,
  },
  heroBadge: {
    padding: "8px 12px",
    borderRadius: 999,
    background: "#ecfeff",
    color: "#0e7490",
    fontSize: 12,
    fontWeight: 900,
  },
  heroLink: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #bfdbfe",
    borderRadius: 999,
    background: "#eff6ff",
    color: "#1d4ed8",
    padding: "8px 12px",
    fontSize: 12,
    fontWeight: 900,
    textDecoration: "none",
  },
  filterPanel: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "center",
    flexWrap: "wrap",
    minWidth: 0,
    padding: 18,
    borderRadius: 20,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  },
  sectionMiniTitle: {
    margin: 0,
    color: "#0f172a",
    fontSize: 13,
    fontWeight: 900,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  mutedText: {
    margin: "6px 0 0",
    color: "#64748b",
    fontSize: 14,
    lineHeight: 1.45,
  },
  filterControls: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  filterInput: {
    minWidth: 210,
    maxWidth: "100%",
    border: "1px solid #cbd5e1",
    borderRadius: 999,
    padding: "10px 12px",
    color: "#0f172a",
    fontWeight: 800,
    background: "#ffffff",
  },
  dashboardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 540px), 1fr))",
    gap: 18,
    width: "100%",
    minWidth: 0,
    alignItems: "start",
  },
  detailCardWrap: {
    width: "min(100%, 900px)",
  },
  card: {
    display: "grid",
    gap: 18,
    minWidth: 0,
    overflow: "hidden",
    padding: 20,
    borderRadius: 24,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    boxShadow: "0 16px 40px rgba(15, 23, 42, 0.07)",
  },
  cardTop: {
    display: "flex",
    justifyContent: "space-between",
    gap: 14,
    alignItems: "flex-start",
    flexWrap: "wrap",
    minWidth: 0,
  },
  cardTitle: {
    margin: "6px 0 0",
    color: "#0f172a",
    fontSize: 18,
    lineHeight: 1.25,
    wordBreak: "break-word",
    overflowWrap: "anywhere",
  },
  cardSubtitle: {
    margin: "6px 0 0",
    color: "#334155",
    fontSize: 13,
    fontWeight: 800,
    overflowWrap: "anywhere",
  },
  fileName: {
    margin: "4px 0 0",
    color: "#64748b",
    fontSize: 13,
    overflowWrap: "anywhere",
  },
  statusStack: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  statusPill: {
    display: "inline-flex",
    padding: "7px 10px",
    borderRadius: 999,
    background: "#ecfeff",
    color: "#0e7490",
    fontSize: 11,
    fontWeight: 900,
    whiteSpace: "nowrap",
  },
  attentionPill: {
    display: "inline-flex",
    padding: "7px 10px",
    borderRadius: 999,
    background: "#fef3c7",
    color: "#92400e",
    fontSize: 11,
    fontWeight: 900,
    whiteSpace: "nowrap",
  },
  dangerPill: {
    display: "inline-flex",
    padding: "7px 10px",
    borderRadius: 999,
    background: "#fee2e2",
    color: "#b91c1c",
    border: "1px solid #fecaca",
    fontSize: 11,
    fontWeight: 900,
    whiteSpace: "nowrap",
  },
  coverageGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(230px, 1fr))",
    gap: 12,
    minWidth: 0,
  },
  coverageShell: {
    minWidth: 0,
    padding: 14,
    borderRadius: 18,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  },
  coverageTitle: {
    margin: 0,
    color: "#0f172a",
    fontSize: 13,
    fontWeight: 900,
  },
  coverageRow: {
    display: "grid",
    gridTemplateColumns: "auto minmax(72px, 1fr) auto",
    gap: 10,
    alignItems: "center",
    marginTop: 10,
    minWidth: 0,
  },
  coverageFlow: {
    color: "#0f172a",
    fontSize: 14,
    whiteSpace: "nowrap",
  },
  coverageBar: {
    minWidth: 0,
    color: "#2563eb",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: 15,
    fontWeight: 900,
    letterSpacing: "0.02em",
    overflow: "hidden",
    textOverflow: "clip",
    whiteSpace: "nowrap",
  },
  coveragePercent: {
    color: "#0f172a",
    fontSize: 14,
    whiteSpace: "nowrap",
  },
  funnelShell: {
    display: "grid",
    gap: 10,
    minWidth: 0,
    padding: 14,
    borderRadius: 18,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  },
  funnelTitle: {
    margin: 0,
    color: "#0f172a",
    fontSize: 13,
    fontWeight: 900,
  },
  funnelRows: {
    display: "grid",
    gap: 8,
    minWidth: 0,
  },
  funnelRow: {
    display: "grid",
    gridTemplateColumns: "150px 64px minmax(80px, 1fr) 58px",
    gap: 10,
    alignItems: "center",
    minWidth: 0,
  },
  funnelLabel: {
    color: "#334155",
    fontSize: 13,
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  funnelValue: {
    color: "#0f172a",
    fontSize: 13,
    textAlign: "right",
    whiteSpace: "nowrap",
  },
  funnelBar: {
    minWidth: 0,
    color: "#2563eb",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: 15,
    fontWeight: 900,
    letterSpacing: "0.02em",
    overflow: "hidden",
    textOverflow: "clip",
    whiteSpace: "nowrap",
  },
  funnelPercent: {
    color: "#0f172a",
    fontSize: 12,
    fontWeight: 900,
    textAlign: "right",
    whiteSpace: "nowrap",
  },
  funnelFooter: {
    display: "flex",
    gap: 14,
    flexWrap: "wrap",
    color: "#475569",
    fontSize: 12,
    fontWeight: 800,
  },
  cardActions: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    alignItems: "center",
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
    padding: "0 16px",
    borderRadius: 999,
    border: "1px solid #0f172a",
    background: "#0f172a",
    color: "#ffffff",
    fontSize: 12,
    fontWeight: 900,
    textDecoration: "none",
  },
  secondaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
    padding: "0 16px",
    borderRadius: 999,
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    color: "#0f172a",
    fontSize: 12,
    fontWeight: 900,
    textDecoration: "none",
  },
  allocatedButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
    padding: "0 16px",
    borderRadius: 999,
    border: "1px solid #86efac",
    background: "#dcfce7",
    color: "#166534",
    fontSize: 12,
    fontWeight: 900,
    cursor: "not-allowed",
    opacity: 0.72,
  },
  notice: {
    padding: 18,
    borderRadius: 20,
    border: "1px solid #bfdbfe",
    background: "#eff6ff",
    color: "#1e3a8a",
    fontWeight: 800,
  },
  errorNotice: {
    padding: 18,
    borderRadius: 20,
    border: "1px solid #fecaca",
    background: "#fef2f2",
    color: "#991b1b",
    fontWeight: 800,
  },
  emptyCard: {
    padding: 22,
    borderRadius: 22,
    border: "1px dashed #cbd5e1",
    background: "#f8fafc",
    color: "#64748b",
  },
};

export default styles;
