export const fakeTcReport = {
  id: "TC_20260528_052534_ZA7423_MDCN",
  tcId: "TC_20260528_052534_ZA7423_MDCN",
  reportType: "TC_FINAL_REPORT",
  trnType: "METER_DISCONNECTION",
  lmPcode: "ZA7423",
  fileName: "TC_UPLOAD_DCN_TEMPLATE_v1.csv",
  status: "DRAFT",

  summary: {
    uploadedRows: 300,
    tcRows: 300,
    bgoReadyRows: 200,
    bgoNotReadyRows: 100,
    bgoRows: 200,
    trnsCreated: 200,
    executionAccessRows: 150,
    executionNoAccessRows: 50,
    finalSuccessfulRows: 150,
    finalUnsuccessfulRows: 150,
    finalPendingRows: 0,
    dataMismatchRows: 1,
  },

  created: {
    at: "2026-05-28T05:25:34.000Z",
    byUid: "demo-user",
    byUser: "Demo MNG",
  },

  updated: {
    at: "2026-05-28T08:10:00.000Z",
    byUid: "system",
    byUser: "iREPS System",
  },

  finalised: {
    at: null,
    byUid: null,
    byUser: null,
  },
};

export const fakeTcReportRows = [
  {
    id: "TC_20260528_052534_ZA7423_MDCN_R000001",
    tcId: "TC_20260528_052534_ZA7423_MDCN",
    rowNo: "1",

    refs: {
      tcRowId: "TC_20260528_052534_ZA7423_MDCN_R000001",
      bgoRowId: "TC_20260528_052534_ZA7423_MDCN_R000001",
      trnId: "TRN_MDCN_20260528_061500_04085348920",
    },

    upload: {
      meterNo: "04085348920",
      meterPhase: "Single Phase",
      meterType: "electricity",
      linkedAccountNo: "ACC001",
      premiseAddress: "192 Kruger Street Mpumelelo",
      premisePropertyType: "Residential",
      actionReason: "Credit control disconnection",
      wardNo: "6",
      geofence: "GF Kruger Mpumelelo",
      meterStatus: "CONNECTED",
      erfNo: "5320",
    },

    ireps: {
      found: true,
      astId: "AST_04085348920",
      astNo: "04085348920",
      meterPhase: "Single Phase",
      meterType: "electricity",
      linkedAccountNo: "ACC001",
      premiseId: "PREM_5320_001",
      premiseAddress: "192 Kruger Street Mpumelelo",
      premisePropertyType: "Residential",
      wardNo: "6",
      wardPcode: "ZA7423006",
      geofenceRefs: [{ id: "GF001", name: "GF Kruger Mpumelelo" }],
      meterStatus: "CONNECTED",
      erfNo: "5320",
    },

    tc: {
      validationState: "VALIDATED",
      found: true,
      eligible: true,
      hasGeofence: true,
      readyForBgo: true,
      readinessState: "READY_FOR_BGO",
      readinessReason: "READY",
    },

    bgo: {
      ready: true,
      used: true,
      batchId: "TC_20260528_052534_ZA7423_MDCN_BGO_GF001",
      bgoRowId: "TC_20260528_052534_ZA7423_MDCN_R000001",
      usedAt: "2026-05-28T06:15:00.000Z",
    },

    trn: {
      created: true,
      trnId: "TRN_MDCN_20260528_061500_04085348920",
      trnType: "METER_DISCONNECTION",
      workflowState: "COMPLETED",
      assignedTo: "FWR Demo User",
      assignedToUid: "fwr-demo-001",
    },

    execution: {
      completed: true,
      hasAccess: true,
      outcome: "SUCCESS",
      reason: "Disconnected successfully",
      executedBy: "FWR Demo User",
      executedByUid: "fwr-demo-001",
      executedAt: "2026-05-28T08:00:00.000Z",
      finalMeterStatus: "DISCONNECTED",
    },

    flags: {
      meterNoMatch: true,
      meterPhaseMatch: true,
      meterTypeMatch: true,
      linkedAccountNoMatch: true,
      premiseAddressMatch: true,
      premisePropertyTypeMatch: true,
      wardNoMatch: true,
      geofenceMatch: true,
      meterStatusMatch: true,
      erfNoMatch: true,
      flagCodes: [],
    },

    finalDecision: {
      code: "SUCCESSFUL",
      label: "Successful",
      successful: true,
      reasonCode: "DISCONNECTION_SUCCESSFUL",
      requiredAction: "No further LM action required",
    },
  },
  {
    id: "TC_20260528_052534_ZA7423_MDCN_R000002",
    tcId: "TC_20260528_052534_ZA7423_MDCN",
    rowNo: "2",

    refs: {
      tcRowId: "TC_20260528_052534_ZA7423_MDCN_R000002",
      bgoRowId: "TC_20260528_052534_ZA7423_MDCN_R000002",
      trnId: "TRN_MDCN_20260528_061501_04085348921",
    },

    upload: {
      meterNo: "04085348921",
      meterPhase: "Single Phase",
      meterType: "electricity",
      linkedAccountNo: "ACC002",
      premiseAddress: "194 Kruger Street Mpumelelo",
      premisePropertyType: "Residential",
      actionReason: "Credit control disconnection",
      wardNo: "6",
      geofence: "GF Kruger Mpumelelo",
      meterStatus: "CONNECTED",
      erfNo: "5321",
    },

    ireps: {
      found: true,
      astId: "AST_04085348921",
      astNo: "04085348921",
      meterPhase: "Single Phase",
      meterType: "electricity",
      linkedAccountNo: "ACC002",
      premiseId: "PREM_5321_001",
      premiseAddress: "194 Kruger Street Mpumelelo",
      premisePropertyType: "Residential",
      wardNo: "6",
      wardPcode: "ZA7423006",
      geofenceRefs: [{ id: "GF001", name: "GF Kruger Mpumelelo" }],
      meterStatus: "CONNECTED",
      erfNo: "5321",
    },

    tc: {
      validationState: "VALIDATED",
      found: true,
      eligible: true,
      hasGeofence: true,
      readyForBgo: true,
      readinessState: "READY_FOR_BGO",
      readinessReason: "READY",
    },

    bgo: {
      ready: true,
      used: true,
      batchId: "TC_20260528_052534_ZA7423_MDCN_BGO_GF001",
      bgoRowId: "TC_20260528_052534_ZA7423_MDCN_R000002",
      usedAt: "2026-05-28T06:15:00.000Z",
    },

    trn: {
      created: true,
      trnId: "TRN_MDCN_20260528_061501_04085348921",
      trnType: "METER_DISCONNECTION",
      workflowState: "COMPLETED",
      assignedTo: "FWR Demo User",
      assignedToUid: "fwr-demo-001",
    },

    execution: {
      completed: true,
      hasAccess: false,
      outcome: "NO_ACCESS",
      reason: "Gate locked. Customer not available.",
      executedBy: "FWR Demo User",
      executedByUid: "fwr-demo-001",
      executedAt: "2026-05-28T08:05:00.000Z",
      finalMeterStatus: "CONNECTED",
    },

    flags: {
      meterNoMatch: true,
      meterPhaseMatch: true,
      meterTypeMatch: true,
      linkedAccountNoMatch: true,
      premiseAddressMatch: true,
      premisePropertyTypeMatch: true,
      wardNoMatch: true,
      geofenceMatch: true,
      meterStatusMatch: true,
      erfNoMatch: true,
      flagCodes: ["NO_ACCESS"],
    },

    finalDecision: {
      code: "UNSUCCESSFUL",
      label: "Unsuccessful",
      successful: false,
      reasonCode: "NO_ACCESS",
      requiredAction: "Schedule revisit or alternative access arrangement",
    },
  },
  {
    id: "TC_20260528_052534_ZA7423_MDCN_R000003",
    tcId: "TC_20260528_052534_ZA7423_MDCN",
    rowNo: "3",

    refs: {
      tcRowId: "TC_20260528_052534_ZA7423_MDCN_R000003",
      bgoRowId: null,
      trnId: null,
    },

    upload: {
      meterNo: "04085348922",
      meterPhase: "Single Phase",
      meterType: "electricity",
      linkedAccountNo: "ACC003",
      premiseAddress: "196 Kruger Street Mpumelelo",
      premisePropertyType: "Residential",
      actionReason: "Credit control disconnection",
      wardNo: "6",
      geofence: "",
      meterStatus: "CONNECTED",
      erfNo: "5322",
    },

    ireps: {
      found: true,
      astId: "AST_04085348922",
      astNo: "04085348922",
      meterPhase: "Single Phase",
      meterType: "electricity",
      linkedAccountNo: "ACC003",
      premiseId: "PREM_5322_001",
      premiseAddress: "196 Kruger Street Mpumelelo",
      premisePropertyType: "Residential",
      wardNo: "6",
      wardPcode: "ZA7423006",
      geofenceRefs: [],
      meterStatus: "CONNECTED",
      erfNo: "5322",
    },

    tc: {
      validationState: "VALIDATED_WITH_EXCEPTIONS",
      found: true,
      eligible: true,
      hasGeofence: false,
      readyForBgo: false,
      readinessState: "NEEDS_GEOFENCE",
      readinessReason: "MATCHED_METER_HAS_NO_GEOFENCE",
    },

    bgo: {
      ready: false,
      used: false,
      batchId: null,
      bgoRowId: null,
      usedAt: null,
    },

    trn: {
      created: false,
      trnId: null,
      trnType: "METER_DISCONNECTION",
      workflowState: null,
      assignedTo: null,
      assignedToUid: null,
    },

    execution: {
      completed: false,
      hasAccess: null,
      outcome: null,
      reason: null,
      executedBy: null,
      executedByUid: null,
      executedAt: null,
      finalMeterStatus: "CONNECTED",
    },

    flags: {
      meterNoMatch: true,
      meterPhaseMatch: true,
      meterTypeMatch: true,
      linkedAccountNoMatch: true,
      premiseAddressMatch: true,
      premisePropertyTypeMatch: true,
      wardNoMatch: true,
      geofenceMatch: false,
      meterStatusMatch: true,
      erfNoMatch: true,
      flagCodes: ["NO_GEOFENCE"],
    },

    finalDecision: {
      code: "BLOCKED",
      label: "Blocked",
      successful: false,
      reasonCode: "NO_GEOFENCE",
      requiredAction: "Create/apply geofence before BGO",
    },
  },
  {
    id: "TC_20260528_052534_ZA7423_MDCN_R000004",
    tcId: "TC_20260528_052534_ZA7423_MDCN",
    rowNo: "4",

    refs: {
      tcRowId: "TC_20260528_052534_ZA7423_MDCN_R000004",
      bgoRowId: null,
      trnId: null,
    },

    upload: {
      meterNo: "04085348923",
      meterPhase: "Single Phase",
      meterType: "electricity",
      linkedAccountNo: "ACC004",
      premiseAddress: "198 Kruger Street Mpumelelo",
      premisePropertyType: "Residential",
      actionReason: "Credit control disconnection",
      wardNo: "6",
      geofence: "GF Kruger Mpumelelo",
      meterStatus: "CONNECTED",
      erfNo: "5323",
    },

    ireps: {
      found: false,
      astId: null,
      astNo: null,
      meterPhase: null,
      meterType: null,
      linkedAccountNo: null,
      premiseId: null,
      premiseAddress: null,
      premisePropertyType: null,
      wardNo: null,
      wardPcode: null,
      geofenceRefs: [],
      meterStatus: null,
      erfNo: null,
    },

    tc: {
      validationState: "VALIDATED_WITH_EXCEPTIONS",
      found: false,
      eligible: false,
      hasGeofence: false,
      readyForBgo: false,
      readinessState: "NOT_FOUND",
      readinessReason: "METER_NOT_FOUND_IN_IREPS",
    },

    bgo: {
      ready: false,
      used: false,
      batchId: null,
      bgoRowId: null,
      usedAt: null,
    },

    trn: {
      created: false,
      trnId: null,
      trnType: "METER_DISCONNECTION",
      workflowState: null,
      assignedTo: null,
      assignedToUid: null,
    },

    execution: {
      completed: false,
      hasAccess: null,
      outcome: null,
      reason: null,
      executedBy: null,
      executedByUid: null,
      executedAt: null,
      finalMeterStatus: null,
    },

    flags: {
      meterNoMatch: false,
      meterPhaseMatch: false,
      meterTypeMatch: false,
      linkedAccountNoMatch: false,
      premiseAddressMatch: false,
      premisePropertyTypeMatch: false,
      wardNoMatch: false,
      geofenceMatch: false,
      meterStatusMatch: false,
      erfNoMatch: false,
      flagCodes: ["METER_NOT_FOUND"],
    },

    finalDecision: {
      code: "UNSUCCESSFUL",
      label: "Unsuccessful",
      successful: false,
      reasonCode: "METER_NOT_FOUND",
      requiredAction: "Correct meter number or register meter in iREPS",
    },
  },
  {
    id: "TC_20260528_052534_ZA7423_MDCN_R000005",
    tcId: "TC_20260528_052534_ZA7423_MDCN",
    rowNo: "5",

    refs: {
      tcRowId: "TC_20260528_052534_ZA7423_MDCN_R000005",
      bgoRowId: null,
      trnId: null,
    },

    upload: {
      meterNo: "04085348924",
      meterPhase: "Single Phase",
      meterType: "electricity",
      linkedAccountNo: "ACC005",
      premiseAddress: "200 Kruger Street Mpumelelo",
      premisePropertyType: "Residential",
      actionReason: "Credit control disconnection",
      wardNo: "6",
      geofence: "GF Kruger Mpumelelo",
      meterStatus: "FIELD",
      erfNo: "5324",
    },

    ireps: {
      found: true,
      astId: "AST_04085348924",
      astNo: "04085348924",
      meterPhase: "Single Phase",
      meterType: "electricity",
      linkedAccountNo: "ACC005",
      premiseId: "PREM_5324_001",
      premiseAddress: "200 Kruger Street Mpumelelo",
      premisePropertyType: "Residential",
      wardNo: "6",
      wardPcode: "ZA7423006",
      geofenceRefs: [{ id: "GF001", name: "GF Kruger Mpumelelo" }],
      meterStatus: "FIELD",
      erfNo: "5324",
    },

    tc: {
      validationState: "VALIDATED_WITH_EXCEPTIONS",
      found: true,
      eligible: false,
      hasGeofence: true,
      readyForBgo: false,
      readinessState: "NOT_ELIGIBLE",
      readinessReason: "METER_STATUS_NOT_ELIGIBLE_FOR_DCN",
    },

    bgo: {
      ready: false,
      used: false,
      batchId: null,
      bgoRowId: null,
      usedAt: null,
    },

    trn: {
      created: false,
      trnId: null,
      trnType: "METER_DISCONNECTION",
      workflowState: null,
      assignedTo: null,
      assignedToUid: null,
    },

    execution: {
      completed: false,
      hasAccess: null,
      outcome: null,
      reason: null,
      executedBy: null,
      executedByUid: null,
      executedAt: null,
      finalMeterStatus: "FIELD",
    },

    flags: {
      meterNoMatch: true,
      meterPhaseMatch: true,
      meterTypeMatch: true,
      linkedAccountNoMatch: true,
      premiseAddressMatch: true,
      premisePropertyTypeMatch: true,
      wardNoMatch: true,
      geofenceMatch: true,
      meterStatusMatch: true,
      erfNoMatch: true,
      flagCodes: ["NOT_ELIGIBLE_FOR_DCN"],
    },

    finalDecision: {
      code: "UNSUCCESSFUL",
      label: "Unsuccessful",
      successful: false,
      reasonCode: "NOT_ELIGIBLE_FOR_DCN",
      requiredAction: "Review meter status before disconnection operation",
    },
  },
  {
    id: "TC_20260528_052534_ZA7423_MDCN_R000006",
    tcId: "TC_20260528_052534_ZA7423_MDCN",
    rowNo: "6",

    refs: {
      tcRowId: "TC_20260528_052534_ZA7423_MDCN_R000006",
      bgoRowId: null,
      trnId: null,
    },

    upload: {
      meterNo: "04085348925",
      meterPhase: "Single Phase",
      meterType: "electricity",
      linkedAccountNo: "ACC006",
      premiseAddress: "202 Kruger Street",
      premisePropertyType: "Residential",
      actionReason: "Credit control disconnection",
      wardNo: "6",
      geofence: "GF Kruger Mpumelelo",
      meterStatus: "CONNECTED",
      erfNo: "5325",
    },

    ireps: {
      found: true,
      astId: "AST_04085348925",
      astNo: "04085348925",
      meterPhase: "Single Phase",
      meterType: "electricity",
      linkedAccountNo: "ACC006",
      premiseId: "PREM_5325_001",
      premiseAddress: "202 Kruger Street Mpumelelo",
      premisePropertyType: "Residential",
      wardNo: "6",
      wardPcode: "ZA7423006",
      geofenceRefs: [{ id: "GF001", name: "GF Kruger Mpumelelo" }],
      meterStatus: "CONNECTED",
      erfNo: "5325",
    },

    tc: {
      validationState: "VALIDATED",
      found: true,
      eligible: true,
      hasGeofence: true,
      readyForBgo: true,
      readinessState: "READY_FOR_BGO",
      readinessReason: "READY",
    },

    bgo: {
      ready: true,
      used: false,
      batchId: null,
      bgoRowId: null,
      usedAt: null,
    },

    trn: {
      created: false,
      trnId: null,
      trnType: "METER_DISCONNECTION",
      workflowState: null,
      assignedTo: null,
      assignedToUid: null,
    },

    execution: {
      completed: false,
      hasAccess: null,
      outcome: null,
      reason: null,
      executedBy: null,
      executedByUid: null,
      executedAt: null,
      finalMeterStatus: "CONNECTED",
    },

    flags: {
      meterNoMatch: true,
      meterPhaseMatch: true,
      meterTypeMatch: true,
      linkedAccountNoMatch: true,
      premiseAddressMatch: false,
      premisePropertyTypeMatch: true,
      wardNoMatch: true,
      geofenceMatch: true,
      meterStatusMatch: true,
      erfNoMatch: true,
      flagCodes: ["PREMISE_ADDRESS_MISMATCH"],
    },

    finalDecision: {
      code: "PENDING",
      label: "Pending BGO",
      successful: false,
      reasonCode: "READY_FOR_BGO_NOT_USED",
      requiredAction: "Proceed to BGO",
    },
  },
];
