export const LOOKUPS_COLLECTION = "irepsSelectLookups";

export const LOOKUP_STATUSES = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  DISABLED: "DISABLED",
  ARCHIVED: "ARCHIVED",
};

export const OPTION_STATUSES = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  DISABLED: "DISABLED",
  ARCHIVED: "ARCHIVED",
};

export const ADMIN_LOOKUP_ACTIONS = {
  LIST_LOOKUPS: "LIST_LOOKUPS",
  GET_LOOKUP: "GET_LOOKUP",

  CREATE_LOOKUP: "CREATE_LOOKUP",
  UPDATE_LOOKUP: "UPDATE_LOOKUP",
  PUBLISH_LOOKUP: "PUBLISH_LOOKUP",
  DISABLE_LOOKUP: "DISABLE_LOOKUP",
  ARCHIVE_LOOKUP: "ARCHIVE_LOOKUP",

  CREATE_OPTION: "CREATE_OPTION",
  UPDATE_OPTION: "UPDATE_OPTION",
  PUBLISH_OPTION: "PUBLISH_OPTION",
  DISABLE_OPTION: "DISABLE_OPTION",
  ARCHIVE_OPTION: "ARCHIVE_OPTION",
};

export const LOOKUP_ADMIN_ROLES = ["ADM", "SPU"];

export const DEFAULT_OTHER_CODE = "OTHER";
export const DEFAULT_OTHER_LABEL = "Other";

export const RESERVED_OPTION_CODES = [DEFAULT_OTHER_CODE];

export const LOOKUP_KEY_REGEX = /^[A-Z0-9_]+$/;
export const OPTION_CODE_REGEX = /^[A-Z0-9_]+$/;

export const MAX_LOOKUP_KEY_LENGTH = 120;
export const MAX_OPTION_CODE_LENGTH = 120;
export const MAX_TITLE_LENGTH = 160;
export const MAX_DESCRIPTION_LENGTH = 500;
export const MAX_LABEL_LENGTH = 160;
